### ISSUE TITLE
Error when running example (not an issue)

### ISSUE THREAD

**Issue by thodeveloper** [chrismeller/cybersource#12]
The problem is my wrong setting in currency, now it can run well.

**Comment by chrismeller** [comment]
For future reference for anyone else with a similar problem, the issue was:

> Run: http://domain.ext/tests/auth_amount.php
> 
> Got the error message
> 
> Fatal error: Uncaught exception 'CyberSource\CyberSource_Invalid_Field_Exception' with message 'c:purchaseTotals/c:currency' in D:\cybersource-master\classes\CyberSource\CyberSource.php on line 735

The error message includes the response from CyberSource, which points you at the field having a problem. In this case it's the currency field. The examples are all based in USD, which works fine for the payment processors CyberSource uses in the US, but may not be accepted internationally. Switching the examples to your local currency should resolve this issue.
